server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  location /api/ {
    proxy_pass http://shell-backend:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /rdf-api/ {
    rewrite ^/rdf-api/(.*)$ /api/$1 break;
    proxy_pass http://rdf-backend:3001;
  }

  location /gis-api/ {
    rewrite ^/gis-api/(.*)$ /api/$1 break;
    proxy_pass http://gis-backend:3002;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
